#!/bin/bash

IF_INT=eth0
IF_DMZ=eth2
IF_EXT=eth1

FILE=/tmp/iptables
FILEfilter=/tmp/iptables-filter
FILEnat=/tmp/iptables-nat
FILEmangle=/tmp/iptables-mangle

# outgoing query udp & tcp
# Der Firewall selbst
echo "-A OUTPUT   -j ACCEPT -p udp --dport 53  -m state --state NEW" >> $FILEfilter
echo "-A OUTPUT   -j ACCEPT -p tcp --dport 53  -m state --state NEW" >> $FILEfilter
echo "-A OUTPUT   -j ACCEPT -p tcp --dport 22  -m state --state NEW" >> $FILEfilter
echo "-A OUTPUT   -j ACCEPT -p tcp --dport 80  -m state --state NEW" >> $FILEfilter
echo "-A OUTPUT   -j ACCEPT -p udp --dport 123 -m state --state NEW" >> $FILEfilter
echo "-A INPUT    -j ACCEPT -p tcp --dport 22  -i $IF_INT -m state --state NEW" >> $FILEfilter

echo "-A OUTPUT -p icmp -j ACCEPT" >> $FILEfilter
echo "-A INPUT -p icmp -j ACCEPT" >> $FILEfilter
