#!/bin/bash

# outgoing query udp & tcp
# Der Firewall selbst
IPT_FILTER "-A OUTPUT   -j ACCEPT -p udp --dport 53   $CONNSTATE NEW" 
IPT_FILTER "-A OUTPUT   -j ACCEPT -p tcp --dport 53   $CONNSTATE NEW" 
IPT_FILTER "-A OUTPUT   -j ACCEPT -p tcp --dport 22   $CONNSTATE NEW" 
IPT_FILTER "-A OUTPUT   -j ACCEPT -p tcp --dport 21   $CONNSTATE NEW" 
IPT_FILTER "-A OUTPUT   -j ACCEPT -p tcp --dport 80   $CONNSTATE NEW" 
IPT_FILTER "-A OUTPUT   -j ACCEPT -p tcp --dport 443  $CONNSTATE NEW" 
IPT_FILTER "-A OUTPUT   -j ACCEPT -p tcp --dport 9999 $CONNSTATE NEW" 
IPT_FILTER "-A OUTPUT   -j ACCEPT -p udp --dport 123  $CONNSTATE NEW" 
IPT_FILTER "-A INPUT    -j ACCEPT -p tcp --dport 22   $CONNSTATE NEW" 

IPT_FILTER "-A OUTPUT -p icmp -j ACCEPT" 
IPT_FILTER "-A INPUT  -p icmp -j ACCEPT" 
